kernel:
  image: linuxkit/kernel:4.14.53
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:4fa16c9045d60732dadb04f5d7f5c18d83c6551e
  - linuxkit/runc:v0.4
  - linuxkit/containerd:27a4c84cc8fab2d5ea04342546ecd20453ec99b3
  - linuxkit/ca-certificates:v0.4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.4
services:
  - name: rngd
    image: linuxkit/rngd:v0.4
  - name: dhcpcd
    image: linuxkit/dhcpcd:1fe0db6b1eb7bcb1e4823e61e08afe6d48af7d16
  - name: sshd
    image: linuxkit/sshd:2c7e6e36bd0ffa2b3d950cf9128da89ba3375dbb
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
