kernel:
  image: linuxkit/kernel:4.14.40-rt
  cmdline: "console=tty0"
init:
  - linuxkit/init:4fa16c9045d60732dadb04f5d7f5c18d83c6551e
  - linuxkit/runc:v0.4
  - linuxkit/containerd:27a4c84cc8fab2d5ea04342546ecd20453ec99b3
  - linuxkit/ca-certificates:v0.4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.4
services:
  - name: getty
    image: linuxkit/getty:44730fd0a7c59dbacf5b48b54ba33f551bcf7ef0
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.4
  - name: dhcpcd
    image: linuxkit/dhcpcd:1fe0db6b1eb7bcb1e4823e61e08afe6d48af7d16
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:v0.4
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
trust:
  org:
    - linuxkit
    - library
