kernel:
  image: linuxkit/kernel:4.9.43
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:c7d651da1a5e308c757bc61ce6a41804ea843426
  - linuxkit/runc:838259153885c0c40460379d6cdb7baebaf3fa36
  - linuxkit/containerd:09a21d6606a4011efebacff62a88b956ecac01be
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
  - name: sysfs
    image: linuxkit/sysfs:3ae01a25583ee37a5ff8b09a0e569cb4bd8cf2e9
  - name: dhcpcd
    image: linuxkit/dhcpcd:f3f5413abb78fae9020e35bd4788fa93df4530b7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:cec86f3e1c260c9eafefa80c262fceb40c182ddf
  - name: format
    image: linuxkit/format:158d992b7bf7ab984100c697d7e72161ea7d7382
  - name: mounts
    image: linuxkit/mount:4fe245efb01384e42622c36302e13e386bbaeb08
    command: ["/usr/bin/mountie", "/var/lib/"]
  - name: var
    image: library/alpine:3.6
    command: ["mkdir", "/var/lib/kubeadm"]
    binds:
      - /var/lib:/var/lib
services:
  - name: getty
    image: linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: ntpd
    image: linuxkit/openntpd:0d7befc79842849d0b88d6c3b64200e340d7cf67
  - name: sshd
    image: linuxkit/sshd:505a985d7bd7a90f15eca9cb4dc6ec92789d51a0
  - name: docker
    image: docker:17.06.0-ce-dind
    capabilities:
     - all
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /etc/resolv.conf:/etc/resolv.conf
     - /lib/modules:/lib/modules
     - /run:/run
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
    # VSOCK to unix domain socket forwarding. Forwards guest /var/run/docker.sock
    # to a socket on the host.
  - name: vsudd
    image: linuxkit/vsudd:adad4b6ab7529b6b95339eb0752b0c81a218d185
    binds:
     - /var/run:/var/run
    command: ["/vsudd", "-inport", "2376:unix:/var/run/docker.sock"]
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:9c1545e7b093d1210118de7661d7346393ec195b
    net: host
    command: ["/vpnkit-forwarder", "-vsockPort", "62373"]
  - name: kubernetes-image-cache-common
    image: linuxkitprojects/kubernetes-image-cache-common:ba16b1f8cfe4f415a5946d521e59f67eaeecd9ce
  - name: kubernetes-image-cache-control-plane
    image: linuxkitprojects/kubernetes-image-cache-control-plane:ba16b1f8cfe4f415a5946d521e59f67eaeecd9ce
  - name: kubelet
    image: linuxkitprojects/kubernetes:a843c514368d13b7cf62b881651950d9006bb933-dirty-amd64
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
